module.exports = {
  GET_PRODUCTS: "GET_PRODUCTS",
  PRODUCT_LOADER: "PRODUCT_LOADER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SET_ITEM_CART: "SET_ITEM_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
